name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Установка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Установка зависимостей и сборка
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # 4. Войти в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Сборка Docker-образа
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/sambacrm-business-client:${{ github.sha }} \
            -t ${{ secrets.DOCKER_USERNAME }}/sambacrm-business-client:latest .

      # 6. Публикация Docker-образа
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sambacrm-business-client:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/sambacrm-business-client:latest
